name: words_of_light
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  after_layout: ^1.1.0
  collection: ^1.18.0
  epubz:
  #  path: ../dart-epubz
    git:
      url: https://github.com/FlafyDev/dart-epubz.git
      ref: dev
  http: ^1.2.2
  palette_generator: ^0.3.3
  scroll_snap_list: ^0.9.1
  googleapis: ^13.2.0
  responsive_grid_list: ^1.2.4
  html: ^0.15.0
  path: ^1.8.0
  path_provider: ^2.1.4
  uuid: ^4.5.0
  permission_handler: ^11.3.1
  separated_column: ^3.0.3
  google_mlkit_translation: ^0.11.0
  mime: ^1.0.2
  url_launcher: ^6.1.5
  flutter_html: ^3.0.0-alpha.5
  flutter_inappwebview: ^6.0.0
  flutter_markdown: ^0.7.3+1
  bottom_inset_observer: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.3
  stack: ^0.2.1
  file_picker: ^8.1.2
  flutter_phoenix: ^1.0.0
  archive: ^3.3.1
  flutter_file_dialog: ^3.0.2
  font_awesome_flutter: ^10.1.0
  string_similarity: ^2.0.0
  # shake: ^2.2.0
  image: ^3.1.3
  device_info_plus: ^10.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/variable/
    - assets/fonts/variable/RobotoMono.ttf
    - assets/fonts/variable/Merriweather.ttf
